Add 'aframe-react-stories' to Scenes
aframevr/awesome-aframe pull request #145
Opened 2017-08-07 01:30 UTC by alexanderschnapp

2017-10-09 03:33 UTC, donmccurdy commented
Hi @aschnapp! The second link (http://vrstories.aschnapp.com) seems to be broken.

2017-10-16 02:33 UTC, cvan requested changes
thanks for submitting - just few changes :)

2017-10-16 02:33 UTC, cvan commented on README.md
> -
can you please keep this?

2017-10-16 02:33 UTC, cvan commented on README.md
> +- [aframe-react-stories demo](http://afsdemo.aschnapp.com) - Demo of [aframe-react-stories](http://npmjs.com/aframe-react-stories) module. A module to quickly add social media style stories in VR to
can you use `https:` (not `http:`) URLs?

2017-10-16 02:33 UTC, cvan commented on README.md
> +- [aframe-react-stories demo](http://afsdemo.aschnapp.com) - Demo of [aframe-react-stories](http://npmjs.com/aframe-react-stories) module. A module to quickly add social media style stories in VR to
I would move this from `Scenes` to `Components` section, and perhaps name it as `React Stories` (or just `Stories`) component

2017-10-16 09:36 UTC, cvan requested changes
thanks for updating! looking good - let me know your thoughts on the summary rewording.

2017-10-16 09:36 UTC, cvan commented on README.md
> +- [Stories](https://afsdemo.aschnapp.com) - Demo of [aframe-react-stories](https://npmjs.com/aframe-react-stories) module. A module to quickly add social media style stories in VR to your project.
I would change the URL to `https://www.npmjs.com/package/aframe-react-stories` (since that's what it redirects to

2017-10-16 09:36 UTC, cvan commented on README.md
> +- [Stories](https://afsdemo.aschnapp.com) - Demo of [aframe-react-stories](https://npmjs.com/aframe-react-stories) module. A module to quickly add social media style stories in VR to your project.
thanks for moving and tweaking this.

what do you think of this text?

```
- [Stories](https://afsdemo.aschnapp.com) - Quickly add social media-style stories in VR to your React-based project. [[Demo]](https://www.npmjs.com/package/aframe-react-stories)
```

2017-11-01 20:25 UTC, ngokevin commented
We've discontinued awesome. Thanks!

2017-11-01 20:25 UTC, closed without merging